### ISSUE TITLE
Upgrade node version

### ISSUE THREAD

**Issue by r0skar** [garthenweb/parcel-plugin-css-modules-type-generator#1]
Using `yarn`, I get this error trying to install the plugin:

```
error parcel-plugin-css-modules-type-generator@1.0.0: The engine "node" is incompatible with this module. Expected version "^10.13.0". Got "11.10.0"
```

I can force the installation with `yarn install --ignore-engines` as a workaround and the plugin works great!

**Comment by garthenweb** [comment]
Thank you for letting me know, I just released a new version with a fix!
