### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by tdreyno** [garthenweb/parcel-plugin-css-modules-type-generator#2]
Hi, is Node 10.x really a hard requirement for this package? Parcel itself says:

```
  "engines": {
    "node": ">= 6.0.0"
  },
```

**Comment by garthenweb** [comment]
Parcel transpiles it's code to support nodejs 6, for the plugin I didn't wanted to implement a build step. As nodejs 6s end of life starts in April 2019 I am also not really interested to support it in the future, as it will make things more complicated to maintain.

Anyhow, parcel uses it's original code for nodejs 8 without a build step, I guess this plugin will therefore also work. I need to run the tests, in case they are passing I will adapt the version field!

**Comment by tdreyno** [comment]
Yeah, the main issue npm will not allow this package to be installed in a project that requires node 8.

I totally agree about maintaining node 6 is probably not worth the effort. What about:

```
  "engines": {
    "node": ">= 8.0.0"
  },
```

Thanks

**Comment by garthenweb** [comment]
Yes, I already extended the tests, there should not be an issue: https://travis-ci.org/garthenweb/parcel-plugin-css-modules-type-generator/builds/505130947
I will create a release as soon as possible.

**Comment by tdreyno** [comment]
🙏

**Comment by garthenweb** [comment]
Release is out!
