### ISSUE TITLE
Is it possible to expose a CLI command to generate the `*.d.ts` files?

### ISSUE THREAD

**Issue by rfgamaral** [garthenweb/parcel-plugin-css-modules-type-generator#4]
I have to be honest, I found [`parcel-plugin-typed-css-modules`](https://github.com/Place1/parcel-plugin-typed-css-modules) first and noticed that it exposed a `tcm` (probably from [`typed-css-modules`](https://github.com/Quramy/typed-css-modules)) command that I can execute on the command line and/or with an NPM script.

But I came across your plugin because the other one has a bug when a CSS class uses `composes`, it doesn't generate the name properly. Your plugin doesn't seem to have that issue, which is good and I'm thinking of switching.

However, since `*.d.ts` files are generated, I have them on `.gitignore`, but this presents a problem when checking out a project for the first time or switching to a different branch with changed `*.css` files. We might not have updated `*d.ts` files or, worse than that, some `*.d.ts` files might be missing because we could be checking out a branch with new `*.css` files.

The only way I can think of to fix this issue is to setup a `post-checkout` Git hook to run the command that looks for all `*.css` files and generates the corresponding `*.d.ts` files, but this plugin doesn't expose one, thus my question.

**Comment by rfgamaral** [comment]
You're generating the files yourself, you could expose that as a CLI but I'm assuming that's out of scope of this.

**Comment by garthenweb** [comment]
This is executed together with parcel. As parcel has a cli you could just run parcel. But this will probably will take longer than a stand alone task...
I for my own commit those files to git, but ai can understand that you don't like that approach. It's nothing I would like to support for this plugin, maybe parcel v2 might have some more options to do something like that.

**Comment by rfgamaral** [comment]
I understand :)

One question, though. Would you be open to a PR that would replace the current custom function to generate the `*.d.ts` files with  [`typed-css-modules`](https://github.com/Quramy/typed-css-modules) as a dependency?

**Comment by garthenweb** [comment]
Probably not. There is already one plugin, as you already pointed out in the description, which does exactly that and, as far as I see it, has bugs because of the overhead of syncing parcel with the plugins. I also would assume that it is slower (also this is something I did not measure) because it would parse the file twice in that case.
This was the reason why I created this lean plugin and I don't think it's worth to make it more complex.

**Comment by rfgamaral** [comment]
Well, I might fork your project and mix some of your implementation details with `parcel-plugin-typed-css-modules` implementation details and add some extra features (still thinking about it). Thanks.

**Comment by garthenweb** [comment]
Alright! Feel free to share it in case you do it anyhow, maybe I agree on the approach when I see it :)

**Comment by rfgamaral** [comment]
> Alright! Feel free to share it in case you do it anyhow, maybe I agree on the approach when I see it :)

It's done: https://github.com/rfgamaral/parcel-plugin-typings-for-css-modules
