### ISSUE TITLE
Question: Does this plugin implement any sort of cache to prevent regeneration of unmodified files?

### ISSUE THREAD

**Issue by rfgamaral** [garthenweb/parcel-plugin-css-modules-type-generator#5]
I'm assuming that for very large projects, constantly generation the same, unchanged, `*.d.ts` files, could be very time consuming. Does this plugin skip unmodified `*.css` files with some sort of cache or other mechanism? Or is this plugin really fast even with hundreds of `*.css` files?

**Comment by rfgamaral** [comment]
Never mind, just looked into the source code. It doesn't.

**Comment by garthenweb** [comment]
Parcel has it's own caching and the code is only executed when parcel detects a change of the case file. There might be some potential to optimize further but I think the overhead would be bigger than it's worth it.
I am using this plugin in a bigger project and don't see bigger performance regression, but I also didn't measure so far...

**Comment by rfgamaral** [comment]
Ok, thanks for the clarification :)
